# Generated by Django 3.0.5 on 2020-04-21 21:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olga', '0004_auto_20200420_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='foundationDate',
            field=models.DateField(default=datetime.date(2020, 4, 21), null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employmentDate',
            field=models.DateField(default=datetime.date(2020, 4, 21)),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='startDateSprint',
            field=models.DateField(default=datetime.date(2020, 4, 21)),
        ),
    ]
