# Generated by Django 3.0.5 on 2020-04-22 08:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olga', '0005_auto_20200421_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='foundationDate',
            field=models.DateField(default=datetime.date(2020, 4, 22), null=True),
        ),
        migrations.RemoveField(
            model_name='company',
            name='manager',
        ),
        migrations.AddField(
            model_name='company',
            name='manager',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employmentDate',
            field=models.DateField(default=datetime.date(2020, 4, 22)),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='startDateSprint',
            field=models.DateField(default=datetime.date(2020, 4, 22)),
        ),
    ]
